In [1]:
import pandas as pd
import numpy as np
import sklearn # scikit-learn kutubxonasi
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/gender_submission.csv')
df.head()

FileNotFoundError: ignored

In [3]:
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")


In [4]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [7]:
train.shape

(891, 12)

In [8]:
y=train.Survived
train=train.drop(['Survived'],axis='columns')
datas=pd.concat([train,test],axis=0)
datas.shape

(1309, 11)

In [9]:
per=test.PassengerId

In [10]:
nan_cols = [i for i in datas.columns if datas[i].isnull().any()]
nan_cols

['Age', 'Fare', 'Cabin', 'Embarked']

In [16]:
datas[['Fare','Age']] = datas[['Fare','Age']].fillna(datas[['Fare','Age']].median())

datas['Cabin'] = datas['Cabin'].fillna('none')

In [17]:
datas.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [20]:
datas['Embarked'].value_counts()

S    916
C    270
Q    123
Name: Embarked, dtype: int64

In [19]:
datas['Embarked'] = datas['Embarked'].fillna('S')

In [21]:
datas.tail()

PassengerId  Pclass                          Name     Sex   Age  SibSp  \
413         1305       3            Spector, Mr. Woolf    male  28.0      0   
414         1306       1  Oliva y Ocana, Dona. Fermina  female  39.0      0   
415         1307       3  Saether, Mr. Simon Sivertsen    male  38.5      0   
416         1308       3           Ware, Mr. Frederick    male  28.0      0   
417         1309       3      Peter, Master. Michael J    male  28.0      1   

     Parch              Ticket      Fare Cabin Embarked  
413      0           A.5. 3236    8.0500  none        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500  none        S  
416      0              359309    8.0500  none        S  
417      1                2668   22.3583  none        C

In [23]:
datas = datas.drop(columns=['Name','Ticket','PassengerId'],axis=1)


In [24]:
datas

Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
0         3    male  22.0      1      0    7.2500  none        S
1         1  female  38.0      1      0   71.2833   C85        C
2         3  female  26.0      0      0    7.9250  none        S
3         1  female  35.0      1      0   53.1000  C123        S
4         3    male  35.0      0      0    8.0500  none        S
..      ...     ...   ...    ...    ...       ...   ...      ...
413       3    male  28.0      0      0    8.0500  none        S
414       1  female  39.0      0      0  108.9000  C105        C
415       3    male  38.5      0      0    7.2500  none        S
416       3    male  28.0      0      0    8.0500  none        S
417       3    male  28.0      1      1   22.3583  none        C

[1309 rows x 8 columns]

In [25]:
dataset = pd.get_dummies(datas, drop_first=True)

In [27]:
dataset.tail()

Pclass   Age  SibSp  Parch      Fare  Sex_male  Cabin_A11  Cabin_A14  \
413       3  28.0      0      0    8.0500         1          0          0   
414       1  39.0      0      0  108.9000         0          0          0   
415       3  38.5      0      0    7.2500         1          0          0   
416       3  28.0      0      0    8.0500         1          0          0   
417       3  28.0      1      1   22.3583         1          0          0   

     Cabin_A16  Cabin_A18  ...  Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  \
413          0          0  ...            0         0          0          0   
414          0          0  ...            0         0          0          0   
415          0          0  ...            0         0          0          0   
416          0          0  ...            0         0          0          0   
417          0          0  ...            0         0          0          0   

     Cabin_F4  Cabin_G6  Cabin_T  Cabin_none  Embarked_Q  Embarked_S  
413         0         0        0           1           0           1  
414         0         0        0           0           0           0  
415         0         0        0           1           0           1  
416         0         0        0           1           0           1  
417         0         0        0           1           0           0  

[5 rows x 194 columns]

In [28]:
X=dataset.iloc[:891,:]
test=dataset.iloc[891:,:]

In [30]:
X

Pclass   Age  SibSp  Parch     Fare  Sex_male  Cabin_A11  Cabin_A14  \
0         3  22.0      1      0   7.2500         1          0          0   
1         1  38.0      1      0  71.2833         0          0          0   
2         3  26.0      0      0   7.9250         0          0          0   
3         1  35.0      1      0  53.1000         0          0          0   
4         3  35.0      0      0   8.0500         1          0          0   
..      ...   ...    ...    ...      ...       ...        ...        ...   
886       2  27.0      0      0  13.0000         1          0          0   
887       1  19.0      0      0  30.0000         0          0          0   
888       3  28.0      1      2  23.4500         0          0          0   
889       1  26.0      0      0  30.0000         1          0          0   
890       3  32.0      0      0   7.7500         1          0          0   

     Cabin_A16  Cabin_A18  ...  Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  \
0            0          0  ...            0         0          0          0   
1            0          0  ...            0         0          0          0   
2            0          0  ...            0         0          0          0   
3            0          0  ...            0         0          0          0   
4            0          0  ...            0         0          0          0   
..         ...        ...  ...          ...       ...        ...        ...   
886          0          0  ...            0         0          0          0   
887          0          0  ...            0         0          0          0   
888          0          0  ...            0         0          0          0   
889          0          0  ...            0         0          0          0   
890          0          0  ...            0         0          0          0   

     Cabin_F4  Cabin_G6  Cabin_T  Cabin_none  Embarked_Q  Embarked_S  
0           0         0        0           1           0           1  
1           0         0        0           0           0           0  
2           0         0        0           1           0           1  
3           0         0        0           0           0           1  
4           0         0        0           1           0           1  
..        ...       ...      ...         ...         ...         ...  
886         0         0        0           1           0           1  
887         0         0        0           0           0           1  
888         0         0        0           1           0           1  
889         0         0        0           0           0           0  
890         0         0        0           1           1           0  

[891 rows x 194 columns]

In [31]:
test.shape

(418, 194)

In [32]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
from sklearn.svm import SVC
model = SVC()
model.fit(train_X,train_y)


SVC()

In [36]:
model.score(test_X,test_y)

0.659217877094972

In [37]:
cross_val_score(model,X, y)

array([0.58659218, 0.71348315, 0.68539326, 0.68539326, 0.69101124])

In [38]:
model_C = SVC(C=45,coef0=1)
model_C.fit(train_X,train_y)
model_C.score(test_X,test_y)

0.7877094972067039

In [39]:
cross_val_score(model_C,X, y)

array([0.65363128, 0.78651685, 0.79775281, 0.78089888, 0.84269663])

In [40]:
from sklearn.linear_model import LogisticRegression
model_1=LogisticRegression()
model_1.fit(train_X,train_y)
model_1.score(test_X,test_y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.7877094972067039

In [41]:
cross_val_score(model_1,X, y)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.81005587, 0.79775281, 0.79213483, 0.7752809 , 0.8258427 ])

In [42]:
from sklearn.ensemble import RandomForestClassifier
modl = RandomForestClassifier(n_estimators=35)
modl.fit(train_X,train_y)
modl.score(test_X,test_y)

0.7932960893854749

In [43]:
cross_val_score(modl,X, y)


array([0.7877095 , 0.78089888, 0.85393258, 0.78651685, 0.87078652])

In [44]:
from sklearn.svm import LinearSVC

model_2 = LinearSVC(loss='hinge',dual=True)
model_2.fit(train_X, train_y)
model_2.score(test_X,test_y)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


0.7988826815642458

In [45]:
cross_val_score(model_2,X, y)


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


array([0.80446927, 0.79775281, 0.80337079, 0.78089888, 0.80898876])

In [46]:
from sklearn.ensemble import GradientBoostingClassifier #For Regression
cl = GradientBoostingClassifier(n_estimators=100, learning_rate=0.5, max_depth=3)
cl.fit(train_X,train_y)
cl.score(test_X,test_y)

0.7988826815642458

In [47]:
cross_val_score(cl,X, y)

array([0.82122905, 0.8258427 , 0.86516854, 0.81460674, 0.8258427 ])

In [48]:
predicted=cl.predict(test)

In [49]:
prediction = pd.DataFrame(predicted,columns=['Survived']).to_csv('submissio.csv',index=False)
result=pd.read_csv('submissio.csv')
result=pd.concat([per,result],axis='columns')
#result=result.drop([1459],axis=0)
result.tail()

PassengerId  Survived
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

In [50]:
prediction = pd.DataFrame(result, columns=['PassengerId','Survived']).to_csv('submission.csv',index=False)
results=pd.read_csv('submission.csv')
results.tail()

PassengerId  Survived
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0